apiVersion: v2
name: kudeploy
description: Kudeploy Kubernetes controller.
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: kudeploy-crds
    version: 0.x.x
    repository: file://../kudeploy-crds
  - name: common
    version: 0.x.x
    repository: oci://ghcr.io/community-helm-charts
