apiVersion: v2
name: kudeploy
description: Kudeploy aggregate chart.
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: kudeploy-crds
    alias: crds
    version: 0.x.x
    repository: oci://ghcr.io/kudeploy/helm-charts
    condition: crds.enabled
  - name: kudeploy-controller
    alias: controller
    version: 0.x.x
    repository: oci://ghcr.io/kudeploy/helm-charts
    condition: controller.enabled
