/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthLayoutRouteImport } from './app/auth/layout'
import { Route as AuthenticatedLayoutRouteImport } from './app/_authenticated/layout'
import { Route as InvitePageRouteImport } from './app/invite/page'
import { Route as AuthenticatedPageRouteImport } from './app/_authenticated/page'
import { Route as AuthLoginPageRouteImport } from './app/auth/login/page'
import { Route as AuthenticatedWorkspacesPageRouteImport } from './app/_authenticated/workspaces/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/layout'
import { Route as AuthenticatedWorkspacesCreatePageRouteImport } from './app/_authenticated/workspaces/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/domains/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/$memberId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/volumes/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/volumes/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/terminal/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/source/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/network/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/metrics/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/logs/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/environment/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/deployments/page'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitePageRoute = InvitePageRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthenticatedWorkspacesPageRoute =
  AuthenticatedWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesCreatePageRoute =
  AuthenticatedWorkspacesCreatePageRouteImport.update({
    id: '/workspaces/create/',
    path: '/workspaces/create/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport.update({
    id: '/member-groups',
    path: '/member-groups',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport.update({
    id: '/$memberId/',
    path: '/$memberId/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport.update(
    {
      id: '/$memberGroupId/',
      path: '/$memberGroupId/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteImport.update(
    {
      id: '/services',
      path: '/services',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteImport.update(
    {
      id: '/_project_layout',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport.update(
    {
      id: '/$serviceId',
      path: '/$serviceId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRouteImport.update(
    {
      id: '/volumes/',
      path: '/volumes/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRouteImport.update(
    {
      id: '/settings/',
      path: '/settings/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRouteImport.update(
    {
      id: '/services/',
      path: '/services/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteImport.update(
    {
      id: '/deployments',
      path: '/deployments',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteImport.update(
    {
      id: '/_service_layout',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteImport.update(
    {
      id: '/$deploymentId',
      path: '/$deploymentId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRouteImport.update(
    {
      id: '/volumes/',
      path: '/volumes/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRouteImport.update(
    {
      id: '/terminal/',
      path: '/terminal/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRouteImport.update(
    {
      id: '/source/',
      path: '/source/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRouteImport.update(
    {
      id: '/settings/',
      path: '/settings/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRouteImport.update(
    {
      id: '/network/',
      path: '/network/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRouteImport.update(
    {
      id: '/metrics/',
      path: '/metrics/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRouteImport.update(
    {
      id: '/logs/',
      path: '/logs/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRouteImport.update(
    {
      id: '/environment/',
      path: '/environment/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRouteImport.update(
    {
      id: '/deployments/',
      path: '/deployments/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedPageRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/invite/': typeof InvitePageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/domains/': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/workspaces/$workspaceId/member-groups/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteWithChildren
  '/workspaces/$workspaceId/member-groups/$memberGroupId/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/workspaces/$workspaceId/member-groups/create/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/': typeof AuthenticatedPageRoute
  '/invite': typeof InvitePageRoute
  '/workspaces': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login': typeof AuthLoginPageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/domains': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute
  '/workspaces/$workspaceId/member-groups/$memberGroupId': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/workspaces/$workspaceId/member-groups/create': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedPageRoute
  '/invite/': typeof InvitePageRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/_authenticated/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/_authenticated/workspaces/$workspaceId/domains/': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/_authenticated/workspaces/$workspaceId/member-groups/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/_authenticated/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/_authenticated/workspaces/$workspaceId/member-groups/create/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/deployments/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/environment/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/logs/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/metrics/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/network/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/source/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/terminal/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite/'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/auth/login/'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/member-groups'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/'
    | '/workspaces/create/'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/api-keys/'
    | '/workspaces/$workspaceId/domains/'
    | '/workspaces/$workspaceId/member-groups/'
    | '/workspaces/$workspaceId/members/'
    | '/workspaces/$workspaceId/projects/'
    | '/workspaces/$workspaceId/settings/'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/member-groups/$memberGroupId/'
    | '/workspaces/$workspaceId/member-groups/create/'
    | '/workspaces/$workspaceId/members/$memberId/'
    | '/workspaces/$workspaceId/projects/$projectId/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments'
    | '/workspaces/$workspaceId/projects/$projectId/services/'
    | '/workspaces/$workspaceId/projects/$projectId/settings/'
    | '/workspaces/$workspaceId/projects/$projectId/volumes/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/invite'
    | '/workspaces'
    | '/auth/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/domains'
    | '/workspaces/$workspaceId/member-groups'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/member-groups/$memberGroupId'
    | '/workspaces/$workspaceId/member-groups/create'
    | '/workspaces/$workspaceId/members/$memberId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/invite/'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/'
    | '/auth/login/'
    | '/_authenticated/workspaces/$workspaceId/api-keys'
    | '/_authenticated/workspaces/$workspaceId/member-groups'
    | '/_authenticated/workspaces/$workspaceId/members'
    | '/_authenticated/workspaces/$workspaceId/projects'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/create/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId'
    | '/_authenticated/workspaces/$workspaceId/api-keys/'
    | '/_authenticated/workspaces/$workspaceId/domains/'
    | '/_authenticated/workspaces/$workspaceId/member-groups/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/projects/'
    | '/_authenticated/workspaces/$workspaceId/settings/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
    | '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/'
    | '/_authenticated/workspaces/$workspaceId/member-groups/create/'
    | '/_authenticated/workspaces/$workspaceId/members/$memberId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/volumes/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/deployments/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/environment/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/logs/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/metrics/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/network/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/settings/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/source/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/terminal/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/volumes/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  InvitePageRoute: typeof InvitePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InvitePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/create/': {
      id: '/_authenticated/workspaces/create/'
      path: '/workspaces/create'
      fullPath: '/workspaces/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreatePageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects': {
      id: '/_authenticated/workspaces/$workspaceId/projects'
      path: '/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members': {
      id: '/_authenticated/workspaces/$workspaceId/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups'
      path: '/member-groups'
      fullPath: '/workspaces/$workspaceId/member-groups'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys'
      path: '/api-keys'
      fullPath: '/workspaces/$workspaceId/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/members/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/member-groups/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/domains/': {
      id: '/_authenticated/workspaces/$workspaceId/domains/'
      path: '/domains'
      fullPath: '/workspaces/$workspaceId/domains/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/api-keys/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/$memberId/': {
      id: '/_authenticated/workspaces/$workspaceId/members/$memberId/'
      path: '/$memberId'
      fullPath: '/workspaces/$workspaceId/members/$memberId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/create/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/create/'
      path: '/create'
      fullPath: '/workspaces/$workspaceId/member-groups/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/'
      path: '/$memberGroupId'
      fullPath: '/workspaces/$workspaceId/member-groups/$memberGroupId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout'
      path: ''
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/volumes/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/volumes/'
      path: '/volumes'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/volumes/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments'
      path: '/deployments'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout'
      path: ''
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/$deploymentId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/volumes/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/volumes/'
      path: '/volumes'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/terminal/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/terminal/'
      path: '/terminal'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/source/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/source/'
      path: '/source'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/network/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/network/'
      path: '/network'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/metrics/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/metrics/'
      path: '/metrics'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/logs/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/logs/'
      path: '/logs'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/environment/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/environment/'
      path: '/environment'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/deployments/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/_service_layout/deployments/'
      path: '/deployments'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/deployments/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMembersPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMembersPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutVolumesPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutDeploymentsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutEnvironmentPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLogsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutMetricsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutNetworkPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSettingsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutSourcePageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutTerminalPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutVolumesPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsDeploymentIdLayoutRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdService_layoutLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdDeploymentsLayoutRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  AuthenticatedWorkspacesPageRoute: typeof AuthenticatedWorkspacesPageRoute
  AuthenticatedWorkspacesCreatePageRoute: typeof AuthenticatedWorkspacesCreatePageRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute:
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren,
  AuthenticatedWorkspacesPageRoute: AuthenticatedWorkspacesPageRoute,
  AuthenticatedWorkspacesCreatePageRoute:
    AuthenticatedWorkspacesCreatePageRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  InvitePageRoute: InvitePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
