/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthLayoutRouteImport } from './app/auth/layout'
import { Route as AuthenticatedLayoutRouteImport } from './app/_authenticated/layout'
import { Route as InvitePageRouteImport } from './app/invite/page'
import { Route as AuthenticatedPageRouteImport } from './app/_authenticated/page'
import { Route as AuthLoginPageRouteImport } from './app/auth/login/page'
import { Route as AuthenticatedWorkspacesPageRouteImport } from './app/_authenticated/workspaces/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/layout'
import { Route as AuthenticatedWorkspacesCreatePageRouteImport } from './app/_authenticated/workspaces/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/domains/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/$memberId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/page'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitePageRoute = InvitePageRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthenticatedWorkspacesPageRoute =
  AuthenticatedWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesCreatePageRoute =
  AuthenticatedWorkspacesCreatePageRouteImport.update({
    id: '/workspaces/create/',
    path: '/workspaces/create/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport.update({
    id: '/member-groups',
    path: '/member-groups',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport.update({
    id: '/$memberId/',
    path: '/$memberId/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport.update(
    {
      id: '/$memberGroupId/',
      path: '/$memberGroupId/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRouteImport.update(
    {
      id: '/settings/',
      path: '/settings/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRouteImport.update(
    {
      id: '/services/',
      path: '/services/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport.update(
    {
      id: '/services/$serviceId',
      path: '/services/$serviceId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRouteImport.update(
    {
      id: '/volumes/',
      path: '/volumes/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRouteImport.update(
    {
      id: '/terminal/',
      path: '/terminal/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRouteImport.update(
    {
      id: '/source/',
      path: '/source/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRouteImport.update(
    {
      id: '/settings/',
      path: '/settings/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRouteImport.update(
    {
      id: '/network/',
      path: '/network/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRouteImport.update(
    {
      id: '/metrics/',
      path: '/metrics/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRouteImport.update(
    {
      id: '/logs/',
      path: '/logs/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRouteImport.update(
    {
      id: '/environment/',
      path: '/environment/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedPageRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/invite/': typeof InvitePageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/domains/': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/workspaces/$workspaceId/member-groups/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/member-groups/$memberGroupId/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/workspaces/$workspaceId/member-groups/create/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/': typeof AuthenticatedPageRoute
  '/invite': typeof InvitePageRoute
  '/workspaces': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login': typeof AuthLoginPageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/domains': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/member-groups/$memberGroupId': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/workspaces/$workspaceId/member-groups/create': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedPageRoute
  '/invite/': typeof InvitePageRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/member-groups': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/_authenticated/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/_authenticated/workspaces/$workspaceId/domains/': typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  '/_authenticated/workspaces/$workspaceId/member-groups/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
  '/_authenticated/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  '/_authenticated/workspaces/$workspaceId/member-groups/create/': typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite/'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/auth/login/'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/member-groups'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/'
    | '/workspaces/create/'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/api-keys/'
    | '/workspaces/$workspaceId/domains/'
    | '/workspaces/$workspaceId/member-groups/'
    | '/workspaces/$workspaceId/members/'
    | '/workspaces/$workspaceId/projects/'
    | '/workspaces/$workspaceId/settings/'
    | '/workspaces/$workspaceId/member-groups/$memberGroupId/'
    | '/workspaces/$workspaceId/member-groups/create/'
    | '/workspaces/$workspaceId/members/$memberId/'
    | '/workspaces/$workspaceId/projects/$projectId/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/'
    | '/workspaces/$workspaceId/projects/$projectId/settings/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/invite'
    | '/workspaces'
    | '/auth/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/domains'
    | '/workspaces/$workspaceId/member-groups'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/member-groups/$memberGroupId'
    | '/workspaces/$workspaceId/member-groups/create'
    | '/workspaces/$workspaceId/members/$memberId'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/invite/'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/'
    | '/auth/login/'
    | '/_authenticated/workspaces/$workspaceId/api-keys'
    | '/_authenticated/workspaces/$workspaceId/member-groups'
    | '/_authenticated/workspaces/$workspaceId/members'
    | '/_authenticated/workspaces/$workspaceId/projects'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/create/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId'
    | '/_authenticated/workspaces/$workspaceId/api-keys/'
    | '/_authenticated/workspaces/$workspaceId/domains/'
    | '/_authenticated/workspaces/$workspaceId/member-groups/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/projects/'
    | '/_authenticated/workspaces/$workspaceId/settings/'
    | '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/'
    | '/_authenticated/workspaces/$workspaceId/member-groups/create/'
    | '/_authenticated/workspaces/$workspaceId/members/$memberId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  InvitePageRoute: typeof InvitePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InvitePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/create/': {
      id: '/_authenticated/workspaces/create/'
      path: '/workspaces/create'
      fullPath: '/workspaces/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreatePageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects': {
      id: '/_authenticated/workspaces/$workspaceId/projects'
      path: '/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members': {
      id: '/_authenticated/workspaces/$workspaceId/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups'
      path: '/member-groups'
      fullPath: '/workspaces/$workspaceId/member-groups'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys'
      path: '/api-keys'
      fullPath: '/workspaces/$workspaceId/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/members/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/member-groups/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/domains/': {
      id: '/_authenticated/workspaces/$workspaceId/domains/'
      path: '/domains'
      fullPath: '/workspaces/$workspaceId/domains/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/api-keys/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/$memberId/': {
      id: '/_authenticated/workspaces/$workspaceId/members/$memberId/'
      path: '/$memberId'
      fullPath: '/workspaces/$workspaceId/members/$memberId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/create/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/create/'
      path: '/create'
      fullPath: '/workspaces/$workspaceId/member-groups/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/': {
      id: '/_authenticated/workspaces/$workspaceId/member-groups/$memberGroupId/'
      path: '/$memberGroupId'
      fullPath: '/workspaces/$workspaceId/member-groups/$memberGroupId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
      path: '/volumes'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
      path: '/terminal'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/terminal/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
      path: '/source'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/source/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
      path: '/network'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
      path: '/metrics'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
      path: '/logs'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
      path: '/environment'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsMemberGroupIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsCreatePageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMembersPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMembersPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSourcePageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdTerminalPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesPageRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMemberGroupsLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdDomainsPageRoute,
    AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  AuthenticatedWorkspacesPageRoute: typeof AuthenticatedWorkspacesPageRoute
  AuthenticatedWorkspacesCreatePageRoute: typeof AuthenticatedWorkspacesCreatePageRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute:
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren,
  AuthenticatedWorkspacesPageRoute: AuthenticatedWorkspacesPageRoute,
  AuthenticatedWorkspacesCreatePageRoute:
    AuthenticatedWorkspacesCreatePageRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  InvitePageRoute: InvitePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
