{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kudeploy.fullname" . }}-metrics
  namespace: {{ default (include "kudeploy.namespace" .) .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "kudeploy.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: {{ .Values.metrics.serviceMonitor.path }}
      port: https
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      bearerTokenFile: {{ .Values.metrics.serviceMonitor.bearerTokenFile }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "kudeploy.selectorLabels" . | nindent 6 }}
{{- end }}
