{{- if .Values.server.enabled }}
{{- $values := .Values.server }}
{{- if $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kudeploy.server.serviceAccountName" . }}
  namespace: {{ include "kudeploy.server.namespace" . }}
  labels:
    {{- include "kudeploy.server.labels" . | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
