{{- if and .Values.server.enabled (not .Values.server.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kudeploy.server.secretName" . }}
  namespace: {{ include "kudeploy.server.namespace" . }}
  labels:
    {{- include "kudeploy.server.labels" . | nindent 4 }}
  {{- with .Values.server.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  app-secret: {{ include "kudeploy.server.appSecret" . | b64enc | quote }}
{{- end }}
