apiVersion: v2
name: kudeploy
description: Kudeploy aggregate chart.
type: application
version: 0.3.0
appVersion: latest
dependencies:
  - name: kudeploy-crds
    alias: crds
    version: 0.2.0
    repository: file://../kudeploy-crds
    condition: crds.enabled
  - name: kudeploy-controller
    alias: controller
    version: 0.2.0
    repository: file://../kudeploy-controller
    condition: controller.enabled
  - name: kudeploy-server
    alias: server
    version: 0.3.0
    repository: file://../kudeploy-server
    condition: server.enabled
