apiVersion: v2
name: kudeploy
description: Kudeploy chart.
type: application
version: 0.4.9
dependencies:
  - name: kudeploy-crds
    alias: crds
    version: 0.2.1
    repository: file://../kudeploy-crds
    condition: crds.enabled
  - name: common
    version: 0.1.0
    repository: oci://ghcr.io/community-helm-charts
  - name: postgresql
    version: 2.0.1
    repository: oci://ghcr.io/community-helm-charts
    condition: postgresql.enabled
  - name: valkey
    version: 2.0.1
    repository: oci://ghcr.io/community-helm-charts
    condition: valkey.enabled
