nameOverride: ''
fullnameOverride: ''

crds:
  enabled: true

controller:
  enabled: true
  image:
    registry: ghcr.io
    repository: kudeploy/controller
    tag: ''

client:
  enabled: true
  image:
    registry: ghcr.io
    repository: kudeploy/client
    tag: ''

server:
  enabled: true
  image:
    registry: ghcr.io
    repository: kudeploy/server
    tag: ''

ingress:
  enabled: false
  className: ''
  annotations: {}
  client:
    serviceName: ''
    servicePort: 80
  server:
    serviceName: ''
    servicePort: 4000
  hosts:
    - host: ''
      paths:
        server:
          - path: /api
            pathType: Prefix
        client:
          - path: /
            pathType: Prefix
  tls: []
