apiVersion: v1
kind: Namespace
metadata:
  name: whoami
  labels:
    app.kubernetes.io/managed-by: kudeploy
    kudeploy.com/project: whoami
    kudeploy.com/workspace-id: sample
  annotations:
    kudeploy.com/display-name: Whoami
